# Generated by Django 4.1.5 on 2023-01-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProblemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('problem_description', models.TextField(max_length=300)),
                ('serial_number', models.CharField(max_length=64)),
                ('status_indicator1', models.CharField(choices=[('On', 'on'), ('Off', 'off'), ('Blinking', 'blinking')], max_length=10)),
                ('status_indicator2', models.CharField(choices=[('On', 'on'), ('Off', 'off'), ('Blinking', 'blinking')], max_length=10)),
                ('status_indicator3', models.CharField(choices=[('On', 'on'), ('Off', 'off'), ('Blinking', 'blinking')], max_length=10)),
                ('response_status', models.CharField(blank=True, max_length=300)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
